### ISSUE TITLE
Details about filtering small box

### ISSUE THREAD

**Issue by JDYG** [Chrazqee/SpikingVit#1]
May I ask about the box size you used to filter small bounding boxes in the 1Mpx dataset?

As stated in your paper, the small box size is (60,20) for the 1Mpx dataset. Is this the size before downsampling to 360x640? If (60,20) is for the 1Mpx dataset before downsampling, it would mean that the filtering box size should be (30,10) for the 360x640 resolution.

However, you used a filtering box size of (60,20) for the DSEC-Detection dataset at a resolution of 480x640. This seems unusual because many effective bounding boxes would be removed. According to my statistics, if we use the (30,10) configuration for filtering on the DSEC-Detection dataset, the number of instances for each class—Pedestrian, Two-wheelers, and Cars—would be [15907, 2838, 21355], respectively. However, if we use the (60,20) configuration, the numbers would drop significantly to [5194, 1890, 10853]. 

Could you please clarify this?

**Comment by Chrazqee** [comment]
As for preprocessing of the 1Mpx dataset, we follow the project without any modifications, so you can focus on the project. You can find the project [here](https://github.com/uzh-rpg/RVT). As for the DSEC-Detection dataset, your calculation may be correct, and you can use the (30, 10) settings in your project. Different settings may yield different results. We will also further investigate this setting after my dues. Thank you for your notification.
