### ISSUE TITLE
数据集的内部结构

### ISSUE THREAD

**Issue by Luchen-077** [Chrazqee/SpikingVit#2]
GEN1数据集的内部结构是怎样的，我的是
/GEN1
    /train
        xxx.npy
        xxx.dat
        ...
    /val
        ...
    /test
        ...
复现时出现问题

**Comment by Chrazqee** [comment]
> GEN1数据集的内部结构是怎样的，我的是 /GEN1 /train xxx.npy xxx.dat ... /val ... /test ... 复现时出现问题

这种格式的数据是不正确的，你可以选择处理后验证模型，方便起见，你可以点击[这个](https://download.ifi.uzh.ch/rpg/RVT/datasets/preprocessed/gen1.tar)链接直接下载使用。

**Comment by tzuyu76** [comment]
@Chrazqee 想请问要如何把这种格式的数据转换成链接的那种格式？
